<!-- Phone Number Field -->
<div class="field required">
    <label for="customer-phone" class="label"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
    <div class="control">
        <input type="text" name="customer[phone]" id="customer-phone" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" class="input-text" data-validate="{required:true, 'validate-phoneLax':true}">
    </div>
</div>

<!-- Verify Button -->
<div class="actions-toolbar">
    <div class="primary">
        <button type="button" class="action verify primary" id="verify-phone"><span><?= $block->escapeHtml(__('Verify')) ?></span></button>
    </div>
</div>

<!-- OTP Field (Initially Hidden) -->
<div class="field" id="otp-field" style="display:none;">
    <label for="customer-otp" class="label"><span><?= $block->escapeHtml(__('OTP')) ?></span></label>
    <div class="control">
        <input type="text" name="customer[otp]" id="customer-otp" title="<?= $block->escapeHtmlAttr(__('OTP')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>

<script type="text/javascript">
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('#verify-phone').on('click', function() {
                var phoneNumber = $('#customer-phone').val();
                // Validate the phone number format here if needed

                // Make AJAX call to send OTP
                $.ajax({
                    url: '<?= $block->getUrl('zaintawseel_customerotpverification/account/sendOtp') ?>', // Update URL with your actual AJAX endpoint
                    type: 'POST',
                    data: {
                        'phone_number': phoneNumber
                    },
                    showLoader: true,
                    success: function(response) {
                        // Handle success. For example, show the OTP field if OTP is sent successfully
                        if (response.success) {
                            $('#otp-field').show();
                        } else {
                            // Handle failure. For example, show an error message
                            alert(response.message);
                        }
                    },
                    error: function(response) {
                        // Handle AJAX error
                        alert('Error sending OTP. Please try again.');
                    }
                });
            });
        });
    });
</script>
